---
title: "Bridel"
author: "Noé Bridel"
format: html
---

## Question 1

```{r}
library(dplyr)
library(vroom)
library(here)
```

```{r}
here::i_am("grades-lab.Rproj")
grades <- vroom(here("grades.csv"))
```

## Question 2

```{r}
grades %>%
  select(grade) %>%
  summarise(n=n())
```
The data set contains 44771 grades.

## Question 3

```{r}
grades %>%
  distinct(id, .keep_all = TRUE) %>%
  summarise(n=n())
```
The data set contains 887 students.

## Question 4

```{r}
students <- grades %>%
  distinct(id, group, .keep_all = FALSE) %>%
  slice_sample(n=10)
```

## Question 5

```{r}
library(ggplot2)
ggplot(students, aes(x = id)) + 
  geom_bar() +
  facet_wrap(~ group)
```

## Question 6

```{r}
mean_grade <- grades %>%
  filter(course=="Hunting and Gathering Skills") %>%
  group_by(group) %>%
  summarise(mean_g=mean(grade))
```


```{r}
ggplot(mean_grade,aes(x = group, y=mean_g)) +
  geom_col() 
```

## Question 7

```{r}
ggplot(grades,aes(x = grade)) +
  geom_bar() +
  facet_wrap(~ trimester)
```

## Question 8
```{r}
grade_per_student <- grades %>% 
  distinct(id, group, .keep_all = FALSE) %>%
  group_by(id) %>%
  summarize(n_grade=n(), .groups = 'drop') %>%
  slice_head(n=10)
```


```{r}
grade_per_student %>%
  summarise(min=min(n_grade),
            median=median(n_grade),
            mean=mean(n_grade),
            max=mean(n_grade))
```

## Question 9

```{r}
grade_SSP <- grades %>%
  filter(course=="Shamanism and Spiritual Practices") %>%
  group_by(id, group) %>%
  summarize(n=n()) %>%
  slice_head(n=10)
```

## Question 10

```{r}
number_grade_SSP <- grade_SSP %>%
  group_by(id) %>%
  summarize(n_grades_SSP = n())
```

```{r}
distribution_SSP <- number_grade_SSP %>%
  group_by(n_grades_SSP) %>%
  summarize(n_student_SSP = n())
```


```{r}
ggplot(distribution_SSP, aes(x = factor(n_grades_SSP), y = n_student_SSP)) +
  geom_col()
```

## Question 11

```{r}
ggplot(number_grade_SSP, aes(x = factor(n_grades_SSP))) +  
  geom_bar(aes(fill = group))
```

